<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_et_pb_contact_message_1</name>
   <tag></tag>
   <elementGuidId>c268ac6f-2673-4585-99f0-21ec5203332a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#et_pb_contact_message_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='et_pb_contact_message_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8df1d8a0-a038-40e2-a0e5-b58d51fbd0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>et_pb_contact_message_1</value>
      <webElementGuid>c0cce3d4-d5ea-426c-b802-ee8cc0fb5dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>et_pb_contact_message_1</value>
      <webElementGuid>83cbd987-a551-4ad8-acb2-298c1d4ab8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_contact_message input</value>
      <webElementGuid>07f20103-ad5e-4ac3-8e7a-bd24a6a2c7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required_mark</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>7a8ed22b-a962-4b3e-8f9e-bfff33b796b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field_type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c40bb520-b42e-4abf-8d0f-a4ad26b5ac63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original_id</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>ae3c657f-3415-4b32-a294-671d93519899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Message</value>
      <webElementGuid>89f1479e-77eb-4cd5-ac74-075016767c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et_pb_contact_message_1&quot;)</value>
      <webElementGuid>514dbfb2-c05c-40c4-916c-3eaf5b3778ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='et_pb_contact_message_1']</value>
      <webElementGuid>c784df74-cf26-4a20-8373-c292337bb1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et_pb_contact_form_1']/div[2]/form/p[2]/textarea</value>
      <webElementGuid>45065ae2-83c4-4b8c-b1e0-92196f190c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/p[2]/textarea</value>
      <webElementGuid>3c383962-ff5a-45e2-9837-04c4f58f3715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'et_pb_contact_message_1' and @id = 'et_pb_contact_message_1' and @placeholder = 'Message']</value>
      <webElementGuid>5b1aba3b-4bbb-4a7d-8bac-a7047cf3657c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
