<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Age_col-md-2 col-sm-12</name>
   <tag></tag>
   <elementGuidId>c519c849-7875-4221-a7aa-7b55a66519ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-2.col-sm-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='age-wrapper']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e2dd344-e82f-4497-a39b-760a96f4db1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-2 col-sm-12</value>
      <webElementGuid>9b3c1602-e0fa-4a85-b5ed-da6d4809adb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;age-wrapper&quot;)/div[@class=&quot;col-md-2 col-sm-12&quot;]</value>
      <webElementGuid>ff1d6447-ac1a-45ba-bf21-2e57f0c9afd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='age-wrapper']/div[2]</value>
      <webElementGuid>a461ab0e-b878-45a2-ae5d-14744fea6796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[2]/following::div[1]</value>
      <webElementGuid>5e1ef688-8591-4073-84f1-d19544c6ab9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::div[4]</value>
      <webElementGuid>c0bcfc7d-56d4-493f-a4c0-77c634dbbbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary'])[2]/preceding::div[1]</value>
      <webElementGuid>39f64883-9d32-4847-9d8c-d9f6f47e0f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[2]/preceding::div[4]</value>
      <webElementGuid>4efee4ea-98ed-4238-9a65-36f47c4f705d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div[2]</value>
      <webElementGuid>030f99e6-ab3c-4452-94a1-3fbc6d88415b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
